loomi-dev/bayer-geracao-demanda-client

src/styles/theme/foundations/layerStyles.ts, src/styles/theme/foundations/shadows.ts
Cria layerStyle para cards, que são reutilizados em toda a aplicação
Ir em index.tsx, apagar todo o conteudo do `return`, criar uma box com width e height, e adicionar a prop `layerStyles='card'`
=> Adds layerStyle

src/pages/index.tsx, src/styles/theme/components/index.ts, src/styles/theme/components/radio.ts, src/styles/theme/foundations/colors.ts
Criado o componente de Radio.
- Desenvolvido e adicionado o componente de Radio ao theme.
=> feat: radio component added in theme

package.json, tsconfig.json, yarn.lock
Adicionado o CLI do Chakra
- Adicionado o CLI do Chakra para geração de tokens do tema.
=> feat: chakra cli to generate tokens theme

src/components/DynamicTable/DynamicTable.tsx, src/components/DynamicTable/TableBody.tsx, src/components/DynamicTable/TableHead.tsx, src/components/DynamicTable/index.ts, src/components/index.ts, src/layouts/LayoutWithoutNotifications.tsx, src/styles/theme/components/index.ts, src/styles/theme/components/table.ts, src/styles/theme/foundations/shadows.ts
Desenvolvido o componente de Table.
- Desenvolvido o componente de Table do React Table.
- Criado estilos de variants para o Table do Chakra.
=> feat: added table component in theme

src/api/types.ts
Corrigi a tipagem da response da QueryOpt
=> fix: response type

src/api/planning/endpoints.ts, src/api/planning/types.ts, src/components/DynamicTable/DynamicTable.tsx, src/components/Pagination/Pagination.tsx, src/hooks/usePagination.tsx, src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.tsx, src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx, src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx
Adicionado condicionais para verificar se é ultima página ou primeira página.
- Adicionado condicionais no componente de Pagination para verificar se é primeira página ou ultima página.
1. Acesse a plataforma
=> feat: conditional to decrease or increment pages

src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.tsx, src/modules/customers/pages/CustomerPlanningDetailScreen/CustomerPlanningDetailScreen.tsx, src/modules/customers/pages/CustomerPlanningDetailScreen/index.ts, src/modules/customers/pages/index.ts, src/pages/clientes/[customer_id]/detalhes/[planning_id].tsx, src/pages/clientes/[customer_id]/index.tsx
Cria pagina de detalhes do planejamento do cliente com o layout de notificações incluso
=> Creates customer planning detail layout

src/components/StatCard/StatCard.tsx, src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActionsTable.tsx, src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/PlanningActionResume.tsx
Verifica se existe o id da planning pra poder fazer o request, e corrige o uso de valor default para caso a metrica venha nula
=> Fix requests and metrics in customer planning details 

src/api/customer/endpoints.ts, src/api/customer/types.ts, src/components/Header/Header.tsx, src/modules/customers/pages/CustomerDetailScreen/CustomerDetailScreen.tsx, src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.columns.tsx, src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.columns.tsx, src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx, src/types/global.d.ts
Termina de integrar alguns campos da tabela de clientes, corrige o header no detalhe do cliente e adiciona uma sublabel
=> Finish integrating some table values

src/api/planning/types.ts, src/components/DatePicker/DatePicker.tsx, src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.columns.tsx, src/modules/planning/api/types.ts, src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/CreatePlanningActionDrawerButton.tsx, src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/PlanningActionForm.schema.ts, src/modules/planning/pages/CreatePlanningScreen/components/CreatePlanningActionDrawerButton/SelectDateSection.tsx, src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.columns.tsx, src/styles/theme/externals/react-datepicker.ts, src/types/global.d.ts
Corrigidos as data do planejamento e da criação de ação.
=> fix: dates in planning and planning action

src/api/planning/endpoints.ts, src/api/planning/mutations/index.ts, src/api/planning/mutations/useUpdatePlanningHistoric.ts, src/api/planning/types.ts, src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/PlanningActionResume.tsx
Cria mutation para lidar com envio de planejamento, autorização e recusa do mesmo
- Alteração 1
- Alteração 2
- Alteração 3
=> Creates mutation to update historic

src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerHistoricDrawer/CustomerHistoricDrawer.tsx, src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActionsTable.tsx
Lida com o caso de recusar todo o planejamento
- Alteração 1
- Alteração 2
- Alteração 3
=> Makes request to get all actions

package.json, src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauOptionsSection.tsx, yarn.lock
Adiciona swiper
- Alteração 1
- Alteração 2
- Alteração 3
=> Adds swiper slider

src/api/planning/endpoints.ts, src/api/planning/mutations/index.ts, src/api/planning/mutations/useCreatePlanning.ts, src/api/planning/mutations/useDeletePlanning.ts, src/api/planning/mutations/useUpdatePlanningHistoric.ts, src/api/planning/types.ts, src/modules/planning/api/endpoints.ts, src/modules/planning/api/mutations/index.ts, src/modules/planning/api/mutations/useCreatePlanningAction.ts, src/modules/planning/api/mutations/useDeletePlanningAction.ts, src/modules/planning/api/types.ts, src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx, src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTableAction.tsx, src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx, src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTableAction.tsx
Adicionado mutations de deleção das ações e do planejamento.
- Adicionado mutation para deletar ação e planejamento.
- Adiciona hover nas linhas da tabela e ação de click.
=> feat: hover click in row tables and delete mutations

src/api/customer/endpoints.ts, src/api/customer/types.ts, src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.columns.tsx, src/types/global.d.ts
Corrige os valores renderizados na tabela de clientes
- Alteração 1
- Alteração 2
- Alteração 3
=> Fix customer table values

src/modules/simulator/pages/SimulatorScreen/SimulatorScreen.tsx, src/modules/simulator/pages/SimulatorScreen/components/MinimumNumbersSection/MinimumNumbersSection.tsx, src/modules/simulator/pages/SimulatorScreen/components/MinimumNumbersSection/MinimumNumbersTable.columns.tsx, src/modules/simulator/pages/SimulatorScreen/components/MinimumNumbersSection/MinimumNumbersTable.tsx, src/modules/simulator/pages/SimulatorScreen/components/MinimumNumbersSection/index.ts
Cria a tabela de numeros minimos
- Alteração 1
- Alteração 2
- Alteração 3
=> Creates minimum numbers table

src/components/Sidebar/Sidebar.items.tsx, src/modules/KanbanScreen/KanbanScreen.tsx, src/modules/KanbanScreen/index.ts, src/modules/index.ts, src/pages/planejamento/index.tsx
Cria a pagina de kanban do produtor
- Alteração 1
- Alteração 2
- Alteração 3
=> Creates kanban page

src/api/planning/mutations/useUpdatePlanningHistoric.ts, src/api/planning/types.ts, src/components/Historic/HistoricAccordion.tsx, src/components/Historic/HistoricDoneButton.tsx, src/components/Historic/HistoricHeader.tsx, src/components/Historic/HistoricTitleManager.tsx, src/components/HistoricDrawer/HistoricDrawerStep.tsx, src/components/PastPlanningHistoricSteps/PastPlanningHistoricSteps.tsx, src/components/PastPlanningHistoricSteps/PastPlanningHistoricTitle.tsx, src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPendingPlanningNotification.tsx, src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.columns.tsx, src/modules/customers/pages/CustomerDetailScreen/components/CustomerPlanningTable/CustomerPlanningTable.tsx, src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActions.columns.tsx, src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningActionsTable/CustomerPlanningActionsTable.tsx, src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx, src/modules/planning/pages/CreatePlanningScreen/CreatePlanningScreen.tsx, src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx, src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/SendPlanningFormStep.tsx, src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx, src/styles/theme/components/tooltip.ts, src/types/index.ts
Corrigi estilos e codigos de varios lugares do projeto.
- Alteração 1
- Alteração 2
- Alteração 3
=> fix: all project bad codes

src/api/auth/mutations/useLoginMutation.ts, src/api/auth/mutations/useUpdateUser.ts, src/api/planning/mutations/useCreatePlanning.ts, src/api/planning/mutations/useDeletePlanning.ts, src/api/planning/mutations/useUpdatePlanningHistoric.ts, src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerHistoricDrawer/CustomerHistoricDrawer.tsx, src/modules/planning/api/mutations/useCreatePlanningAction.ts, src/modules/planning/api/mutations/useDeletePlanningAction.ts, src/modules/planning/api/mutations/useUpdatePlanningAction.ts, src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/SendPlanningFormStep.tsx, src/modules/planning/pages/PlanningScreen/components/PlanningStatisticsSection/PlanningStatisticsSection.tsx
Adicionado toast de sucesso e de erro para todas as mutations.
- Adicionado toast de sucesso e erro para as mutations faltantes.
- Alterado as mensagem de sucesso ou de erro de algumas mutations.
=> feat: added toast to all mutations

src/api/trousseau/endpoints.ts, src/modules/trousseau/pages/TrousseauScreen/TrousseauScreen.tsx, src/modules/trousseau/pages/TrousseauScreen/components/SuppliersSection/SupplierCard.tsx, src/modules/trousseau/pages/TrousseauScreen/components/SuppliersSection/SuppliersSection.tsx, src/modules/trousseau/pages/TrousseauScreen/components/SuppliersSection/SuppliersSectionSkeleton.tsx, src/modules/trousseau/pages/TrousseauScreen/components/TrousseauOptionsSection/TrousseauOptionsSection.tsx, src/types/global.d.ts
Integra a parte de fornecedores em enxoval com API
- Alteração 1
- Alteração 2
- Alteração 3
=> Integrates supplier with API

README.md, src/modules/receipts/api/queries/useGetActions.ts, src/modules/receipts/api/types.ts, src/modules/receipts/components/ActionDetails/ActionDetails.tsx, src/modules/receipts/components/ReceiptStatus/ReceiptStatus.tsx, src/modules/receipts/components/Segment/Segment.tsx, src/modules/receipts/pages/ProducerProofsScreen/components/DrawerExpenseReceipt/DrawerExpenseReceipt.tsx, src/modules/receipts/pages/ProducerProofsScreen/components/StockTable/StockTable.columns.tsx, src/modules/receipts/pages/ProducerProofsScreen/components/ViewButton/ViewButton.tsx, src/modules/receipts/pages/ProducerProofsScreen/stores/useActionStore.ts, src/modules/receipts/pages/ReceiptsScreen/ReceiptsScreen.tsx, src/modules/receipts/pages/ReceiptsScreen/components/DrawerExpenseReceipt/DrawerExpenseReceipt.tsx, src/modules/receipts/pages/ReceiptsScreen/components/FinalizedTables/FinalizedTables.columns.tsx, src/modules/receipts/pages/ReceiptsScreen/components/FinalizedTables/FinalizedTables.tsx, src/modules/receipts/pages/ReceiptsScreen/components/RunningTable/RunningTable.columns.tsx, src/modules/receipts/pages/ReceiptsScreen/components/RunningTable/RunningTable.tsx, src/modules/receipts/pages/ReceiptsScreen/components/ViewButton/ViewButton.tsx, src/modules/receipts/pages/ReceiptsScreen/stores/useActionStore.ts, src/modules/simulator/pages/SimulatorScreen/components/HarvestSection/HarvestSlider.tsx, src/modules/simulator/pages/SimulatorScreen/stores/useSimulatorStore.tsx
Breve descrição sobre a issue, dando um contexto do motivo das alterações do pull request.
- Alteração 1
- Alteração 2
- Alteração 3
=> refactor: update md

src/components/filters/CustomerFilter/CustomerFilter.tsx, src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx
Integra o filtro de clientes com a API. Entretanto, a utilização do filtro nao foi implementada, pois foge do escopo da task
- Alteração 1
- Alteração 2
- Alteração 3
=> Integrates customer filter with api

src/components/Balance/BalanceExpirationDate.tsx, src/modules/auth/pages/OnboardingScreen/OnboardingScreen.tsx, src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.columns.tsx, src/modules/receipts/pages/ProducerProofsScreen/ProducerProofsScreen.tsx, src/modules/simulator/pages/SimulatorScreen/components/HarvestSection/HarvestSwitch.tsx
Corrige os textos com base nas correções apontadas na versão 1.0.1
- Alteração 1
- Alteração 2
- Alteração 3
=> Fix text styles from version 1.0.1

src/components/filters/ResourceFilter/ResourceFilter.tsx, src/components/filters/ResourceFilter/index.ts, src/components/filters/index.ts, src/modules/receipts/pages/ProducerProofsScreen/ProducerProofsScreen.tsx
Cria filtro de origem de recurso. o `value` ta vazio pois ainda nao se sabe o valor 
- Alteração 1
- Alteração 2
- Alteração 3
=> Creates resource filter

src/components/Balance/BalanceContainer.tsx, src/components/filters/CustomerFilter/CustomerFilter.tsx, src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.columns.tsx, src/modules/receipts/pages/ReceiptsScreen/components/RunningTable/RunningTable.columns.tsx
Corrige os erros devido a undefined values no lado do RTV
- Alteração 1
- Alteração 2
- Alteração 3
=> Fix undefined values error in rtv

src/api/auth/mutations/useLoginMutation.ts, src/components/NotificationBar/HeaderNotificationBar.tsx, src/components/NotificationBar/NotificationBar.tsx, src/components/NotificationBar/NotificationCard.tsx, src/components/NotificationBar/NotificationsDrawer.tsx, src/components/NotificationBar/components/index.ts, src/middleware.ts, src/styles/theme/components/drawer.ts
Cria drawer para listar as todas as notificações
- Ajustado estrutura do NotificationBar.
- Adicionado drawer para lista as notificações.
=> feat: drawer to list notifications

src/api/auth/endpoints.ts, src/api/auth/types.ts, src/api/harverst/endpoints.ts, src/api/harverst/index.ts, src/api/index.ts, src/api/planning/endpoints.ts, src/api/planning/types.ts, src/components/Balance/BalanceContainer.tsx, src/components/UserProfileDrawer/components/ProfileDetails/ProfileDetails.tsx, src/components/filters/CustomerFilter/CustomerFilter.tsx, src/lib/next-auth/providers/credentials.ts, src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/RegisterFormTabs.tsx, src/modules/customers/pages/CustomerDetailScreen/CustomerDetailScreen.tsx, src/modules/customers/pages/CustomerPlanningDetailScreen/components/CustomerPlanningDetailCards/CustomerPlanningDetailCards.tsx, src/modules/planning/pages/PlanningScreen/components/PlanningBalance/PlanningBalance.tsx, src/modules/planning/pages/PlanningScreen/components/PlanningTable/PlanningTable.tsx, src/modules/receipts/pages/ProducerProofsScreen/components/StockTable/StockTable.columns.tsx, src/modules/receipts/pages/ReceiptsScreen/components/FinalizedTables/FinalizedTables.columns.tsx, src/types/global.d.ts, src/types/next-auth.d.ts
Breve descrição sobre a issue, dando um contexto do motivo das alterações do pull request.
- Alteração 1
- Alteração 2
- Alteração 3
=> fix: update user response

src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.columns.tsx, src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx
Esconde as ações de editar e excluir ações na tabela de ações do planejamento
- Alteração 1
- Alteração 2
- Alteração 3
=> Fix not showing edit or delete accepted actions

src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/SendPlanningFormStep.tsx, src/modules/planning/pages/PlanningScreen/components/CreatePlanningButton/CreatePlanningButton.tsx
Corrige modais de erro nao aparecendo
- Alteração 1
- Alteração 2
- Alteração 3
=> Fix modals not showing up

src/api/auth/mutations/useLoginMutation.ts, src/lib/next-auth/providers/credentials.ts, src/middleware.ts, src/modules/auth/pages/OnboardingScreen/OnboardingScreen.tsx
Breve descrição sobre a issue, dando um contexto do motivo das alterações do pull request.
- Alteração 1
- Alteração 2
- Alteração 3
=> Merge develop into main

src/components/NotificationBar/NotificationsDrawer.tsx, src/hooks/index.ts, src/hooks/useInfiniteScroll.tsx
Paginação para o drawer de notificações.
- Hook de infinite scroll.
- Feita a paginação juntamente com o infiniteScroll no drawer de notificações
=> feat: infinite scroll notifications

src/api/customer/endpoints.ts, src/api/customer/types.ts, src/api/receipts/endpoints.ts, src/api/receipts/types.ts, src/components/filters/HarvestFilter/HarvestFilter.tsx, src/modules/customers/pages/CustomersScreen/components/CustomerTable/CustomerTable.tsx, src/modules/receipts/pages/ReceiptsScreenFarmer/ReceiptsScreenFarmer.tsx, src/modules/receipts/pages/ReceiptsScreenFarmer/components/ReceiptsActionsTable/ReceiptsActionsTable.tsx, src/modules/receipts/pages/ReceiptsScreenFarmer/components/ReceiptsSummarySection/ReceiptsSummarySection.tsx
Finaliza integração do filtro de safra
- Alteração 1
- Alteração 2
- Alteração 3
=> Finishes integrating harvest filter

src/api/types.ts, src/components/WarningModal/WarningModal.tsx, src/modules/planning/pages/CreatePlanningScreen/components/PlanningHistoricDrawer/SendPlanningFormStep.tsx, src/modules/planning/pages/PlanningScreen/components/CreatePlanningButton/CreatePlanningButton.tsx
Adiciona mais um modal de erro caso o valor do planejamento seja a baixo de 95%
- Alteração 1
- Alteração 2
- Alteração 3
=> Creates another warning modal

src/components/WarningModal/WarningModal.tsx, src/modules/planning/pages/CreatePlanningScreen/components/UpdatePlanningActionDrawer/UpdatePlanningActionDrawer.tsx
Cria modal de error para error de criação e edição de ação
- Alteração 1
- Alteração 2
- Alteração 3
=> Creates warning modal for create and edit actions error

src/api/receipts/mutations/useUploadFile.ts, src/components/UserProfileDrawer/components/EditProfileForm/EditProfileForm.tsx, src/components/WarningModal/WarningModal.tsx, src/modules/auth/pages/RegisterScreen/components/RegisterFormTabs/RegisterFormTabs.tsx
Breve descrição sobre a issue, dando um contexto do motivo das alterações do pull request.
- Adiciona mensagem de error para EMAIL_ALREADY_TAKEN
- Corrige erro na edição do perfil
- Alteração 3
=> fix some bugs

src/components/NotificationBar/NotificationBar.tsx
Corrigido alguns estilos das notificações, para suporta o scroll.
- Adicionado scroll nas notificações.
- Corrigido overflow do container de notificações.
- Adicionado mensagem de fallback para quando não tiver notificações.
=> feat: styles container notifications

public/assets/icons/GrouperIcon.svg, src/api/notifications/endpoints.ts, src/components/NotificationBar/NotificationBar.tsx, src/components/NotificationBar/NotificationCard.tsx, src/components/NotificationBar/NotificationGrouper.tsx, src/components/NotificationBar/NotificationPlanningAction.tsx, src/components/NotificationBar/NotificationsDrawer.tsx, src/components/icons/GrouperIcon.tsx, src/components/icons/index.ts, src/modules/planning/pages/CreatePlanningScreen/components/PlanningActionsTable/PlanningActionsTable.tsx, src/types/global.d.ts
Adicionado ações no card de notificações.
- Adicionado as ações no card de notificações.
=> feat: added planning actions in notification card
